### ISSUE TITLE
Maple 2018 is not supported

### ISSUE THREAD

**Issue by nbodyphysics** [grtensor/grtensor#30] opened 2018-04-26 18:08 UTC
Looks like issues with procmake. Investigating.

**Comment by gdreid** [comment] 2018-06-11 22:58
Any chance of this being resolved soon? My institution just upgraded to Maple 2018 (removing all previous licenses) and breaking my workflow.

**Comment by nbodyphysics** [comment] 2018-06-11 23:16
I have determined that this is related to procmake (which has been deprecated for some time). 

I started on the code to change it to the modern way of creating procedures, so I know in principle what needs to be done, but this change will also reach into grdef. The change is mostly refactoring to the new scheme - but will require a lot of testing. 

I have parked this for now. If anyone wants to make progress on this (and has done a bit of Maple coding) I would be happy to share my work in progress.

**Comment by gdreid** [comment] 2018-06-11 23:23
I've done a bit of Maple coding, and I'd be happy to take a look, but I am
unsure if I would be of much help.

**Comment by nbodyphysics** [comment] 2018-06-11 23:45
Ok. Let me remind myself of what I was up to, and then I can upload the branch to the source repo and post some ideas about what is needed. I'll post back here once I have that done. 1-2 days from now, I hope.

**Comment by gdreid** [comment] 2018-06-12 00:15
Alright :)

**Comment by nbodyphysics** [comment] 2018-06-12 09:35
I have pushed the Maple2018 branch and updated the Readme with a brief outline of what is required. The example cited (grF_build_contractFn) provides an example. 

https://github.com/grtensor/grtensor3src/tree/maple2018

Important: The maple2018 branch is the one with the changes. You will not see them on the master branch!

**Comment by gdreid** [comment] 2018-06-12 17:22
Thanks!

**Comment by nbodyphysics** [comment] 2018-09-06 09:29
I have started to work on this issue and am making progress. I may have something in a few weeks.

**Comment by grtensor** [comment] 2018-10-07 10:26
Fixed in Version 2.2
Root cause is _Inert_FOR or &for requires 7 args in Maple 2018 and 6 previously. 

Startup now does a test inside a try/catch to detect how many are needed. 

Tested in Maple 2017 and Maple 2018.

**Closed as completed by grtensor** 2018-10-07 10:26 UTC
